spring:
  application:
    #本项目名称
    name: config-client
    #服务注册中心
  cloud:
    zookeeper:
      connect-string: 203.195.246.36:2181
      discovery:
        enabled: true
        register: true
#端口
server:
  port: 8091
