spring:
  application:
    #本项目名称
    name: config-client
  cloud:
    config:
      #配置中心服务器地址配置
      uri: http://localhost:8082/
      profile: default
      label: master
      retry:
        # 配置重试次数，默认为6
        max-attempts: 6
        # 间隔乘数 默认1.1
        multiplier: 1.1
        # 初始重试间隔时间，默认1000ms
        initial-interval: 1000
        # 最大间隔时间，默认2000ms
        max-interval: 2000
    #服务注册中心
    zookeeper:
      connect-string: 203.195.246.36:2181
      discovery:
        enabled: true
        register: true
#端口
server:
  port: 8091
